language: node_js
node_js:
  - "9"
dist: trusty
sudo: false

branches:
  only:
  - master

cache:
  directories:
    - node_modules

install:
  - npm install -g yarn

script:
  - yarn lint
  - yarn build --base-href /simple-webapp/
  - mv dist/simple-webapp/index.html dist/simple-webapp/404.html
deploy:
  provider: pages
  skip_cleanup: true
  local_dir: dist/simple-webapp
  on:
    branch: master
